title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
url: https://earth.tyagi.app/
favicon_ico: "/assets/img/favicon.ico"
